verbose: 1

# Set if you want to process the .root -> .pt 
# False means you want to create the graphs from .root 
init_from_processed: False

# Variables to manage the root file
root_folder_path: /sps/t2k/eleblevec/datasets/root_datasets/before_april
tree_name: 'root_event' # depending on wcsimroot_to_root
root_file_names:
  - e_mu_500MeV_10events_each.root
  - e_mu_500MeV_10events_each_xx.root


# Where to save the dataset containing the graphs
graph_folder_path: /sps/t2k/eleblevec/WCSimPackage/GraphDatasets

graph_file_names:
  - data_1.pt

# How many events to store (starting from event 0)
# for EACH .root file
# null means all the events
nb_datapoints: 15

train_data_info: 
  keys : ['time', 'charge']
  types: ['float32', 'float32']

label_data_info:
  keys : ['eventType']
  types: ['int16']

edge_data_info:
  keys : ['hitx', 'hity', 'hitz']
  types: ['float16', 'float16', 'float16']

# If the data shoudl be stored as torch.Tensor. 
# For now only 'Yes' is supported
to_torch_tensor: True



        
